# action.yml
name: 'kicad render pcb'
description: 'Render KiCad PCBs top, bottom optionally render and gif or mp4 of the PCB rotating'
inputs:
  pcb_file:  # id of input
    description: 'Path to your .kicad_pcb'
    required: true
  output_path:
    description: 'Path to where top.png and bottom.png should be created'
    required: true
  zoom:
    description: 'Camera zoom, default 1'
    required: false
  background:
    description: 'Image background. Options: transparent, opaque. Default: opaque for JPEG, transparent for PNG'
    required: false
    default: 'opaque'
  animation:
    description: 'If an animation of the PCB rotating should be rendered (mp4 or gif) (background dose not apply)'
    required: false
  prefix:
    description: 'Set a prefix for the images diffrent from project name'
    required: false
  pre_render:
    description: 'Path to shell file which will be sourced before rendering. This can be used to e.g. install missing fonts or set configuration via enviromet variables.'
    required: false
  kicad_cli_options:
    description: 'Add varios cli options that are not exposed by the action'
    required: false
  docker_image:
    default: 'docker://ghcr.io/linalinn/kicad-render:9.0'
runs:
  using: 'docker'
  image: '${{ inputs.docker_image }}'
  args:
    - bash
    - -c 
    - if [ -n "$INPUT_PRE_RENDER" ]; 
      then source "${INPUT_PRE_RENDER}";fi;
      if [ -n "$INPUT_PREFIX" ];
      then export PREFIX_OPTION=" -p $INPUT_PREFIX ";fi;
      if [ -n "$INPUT_ANIMATION" ]; then 
      KICAD_CLI_OPTIONAL_ARGS="$INPUT_KICAD_CLI_OPTIONS" render-pcb.sh 
      -f "$INPUT_PCB_FILE" 
      -o "$INPUT_OUTPUT_PATH" 
      -b "$INPUT_BACKGROUND" 
      -z "$INPUT_ZOOM" 
      $PREFIX_OPTION 
      -a "$INPUT_ANIMATION"; else 
      KICAD_CLI_OPTIONAL_ARGS="$INPUT_KICAD_CLI_OPTIONS" render-pcb.sh -f "$INPUT_PCB_FILE" 
      -o "$INPUT_OUTPUT_PATH" 
      -b "$INPUT_BACKGROUND" 
      $PREFIX_OPTION 
      -z "$INPUT_ZOOM"; fi

