# action.yml
name: 'kicad render pcb'
description: 'Render KiCad PCBs top, bottom optionally render and gif or mp4 of the PCB rotating'
inputs:
  pcb_file:  # id of input
    description: 'Path to your .kicad_pcb'
    required: true
  output_path:
    description: 'path to where top.png and bottom.png should be created'
    required: true
  zoom:
    description: 'Camera zoom, default 1'
    required: false
  background:
    description: 'Image background. Options: transparent, opaque. Default: transparent for PNG, opaque for JPEG'
    required: false
    default: 'transparent'
  animation:
    description: 'If an animation of the PCB rotating should be rendered (mp4 or gif) (background dose not apply)'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/linalinn/kicad-render:main'
  args:
    - bash
    - -c 
    - if [ -n "$INPUT_ANIMATION" ]; then render-pcb.sh -f "$INPUT_PCB_FILE" -o "$INPUT_OUTPUT_PATH" -b "$INPUT_BACKGROUND" -z "$INPUT_ZOOM" -a "$INPUT_ANIMATION"; else render-pcb.sh -f "$INPUT_PCB_FILE" -o "$INPUT_OUTPUT_PATH" -b "$INPUT_BACKGROUND" -z "$INPUT_ZOOM"; fi

