FROM ubuntu:24.04 as ubuntu-kicad-nightly

ARG DEBIAN_FRONTEND=noninteractive

ARG VERSION=no-version

ENV VERSION=$VERSION

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:kicad/kicad-dev-nightly && \
    apt-get install kicad-nightly ffmpeg -y && \ 
    rm -rf /var/lib/apt/lists/*

FROM ubuntu-kicad-nightly

COPY *.sh /usr/bin/

RUN chmod +rx /usr/bin/render-pcb.sh && chmod +rx /usr/bin/kicad_animation.sh

WORKDIR /pwd