name: build kicad-render image
on:
  push:
    paths:
    - Dockerfile
    - '*.sh'
    - .github/workflows/image.yaml

jobs:

  push_to_registry:
    name: Build, Test and Push
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run:  echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image dev
        if: github.ref_name != github.event.repository.default_branch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "VERSION=${{ github.sha }}"
          cache-to: "type=registry,ref=ghcr.io/linalinn/kicad-render:cache-${{ github.ref_name }}"
          cache-from: "type=registry,ref=ghcr.io/linalinn/kicad-render:cache-${{ github.ref_name }}"
          load: true
          tags: "ghcr.io/linalinn/kicad-render:${{ github.ref_name }}"

      - name: simple render
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }} render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb" && test -s "/pwd/.github/tests/test pcb/test_top.png"
      - name: simple render with output path
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }} render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb" -o "/pwd/images" && test -s "/pwd/images/top.png"
      - name: simple render with filename prefix
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }} render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb" -p fp && test -s "/pwd/.github/tests/test pcb/fp_top.png"
      - name: simple render with output path and filename prefix
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }}  render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb" -o "/pwd/images" -p fp && test -s "$/pwd/images/fp_top.png"
      - name: simple render with zoom
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }} render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb" -o "/pwd/images" -z "0.5" && test -s "/pwd/images/top.png"
      - name: render with animation
        run: docker run -v ${GITHUB_WORKSPACE}:/pwd --rm ghcr.io/linalinn/kicad-render:${{ github.ref_name }} render-pcb.sh -f "/pwd/.github/tests/test pcb/test.kicad_pcb"  -o "/pwd/images" -a "gif" && test -s "/pwd/images/rotating.gif"

      - name: push docker image dev
        if: github.ref_name != github.event.repository.default_branch
        run: |
          docker tag ghcr.io/linalinn/kicad-render:${{ github.ref_name }} ghcr.io/linalinn/kicad-render:9.0-dev
          docker tag ghcr.io/linalinn/kicad-render:${{ github.ref_name }} ghcr.io/linalinn/kicad-render:9.0-dev-${{ steps.date.outputs.date }}
          docker push ghcr.io/linalinn/kicad-render:9.0-dev
          docker push ghcr.io/linalinn/kicad-render:9.0-dev-${{ steps.date.outputs.date }}

      - name: push docker image
        if: github.ref_name == github.event.repository.default_branch
        run: |
          docker tag ghcr.io/linalinn/kicad-render:${{ github.ref_name }} ghcr.io/linalinn/kicad-render:9.0
          docker tag ghcr.io/linalinn/kicad-render:${{ github.ref_name }} ghcr.io/linalinn/kicad-render:9.0-${{ steps.date.outputs.date }}
          docker push ghcr.io/linalinn/kicad-render:9.0
          docker push ghcr.io/linalinn/kicad-render:9.0-${{ steps.date.outputs.date }}
